### ISSUE TITLE
Cipher with version:1 not found in any of the configured SymmetricEncryption ciphers

### ISSUE THREAD

**Issue by MorneL** [rocketjob/symmetric-encryption#103]
Ruby version: 
2.2.2
Symmetric Encryption Version: 
3.7.2
Rails version: 
4.2.4
Exception/stack trace:
Cipher with version:1 not found in any of the configured SymmetricEncryption ciphers

We have been using Cipher for 4 years and haven't made any changes to the codebase surrounding it. It's been working perfectly, encrypting and decrypting.

Recently we experienced a few records encrypting with the wrong version or something. When I use object.valid? it returns with the exception above, even though that is the version we are using.

I don't know where to start debugging this even.

**Comment by MorneL** [comment]
Figured out the issue, we had a delayed job worker with the wrong permissions. It wasn't able to read the config file.

**Comment by sindhuja-sid** [comment]
HI I am facing same issue can you help resolving this
