### ISSUE TITLE
New versions on RubyGems

### ISSUE THREAD

**Issue by le0pard** [rocketjob/symmetric-encryption#126]
Hello, @reidmorrison

Thanks for gem and your work. I noticed, that latest releases of the gem is not published at Rubygems - https://rubygems.org/gems/symmetric-encryption No 4.3.0 and 4.3.1 versions.

Is this expected behavior for this versions of the library?

**Comment by reidmorrison** [comment]
I ran into a few challenges with the new encrypted attribute type for Rails 5. Finally resolved the type conversions and added several tests. The v4.3.0 gem is now available.
