### ISSUE TITLE
Uniqueness validation is not working

### ISSUE THREAD

**Issue by Piioo** [rocketjob/symmetric-encryption#143]
### Environment

Provide at least:
* ruby 2.6.3p62
* Symmetric Encryption 4.3.2
* Rails

### Expected Behavior
```ruby
attribute :foo, :encrypted
validates :foo, uniqueness: { allow_blank: true }
```
The uniqueness validation should work correct

### Actual Behavior

Right now the validations seems not to work.

The Foo class is not encrypting foo, to get the data how it is in the DB for this example.
```ruby
[26] pry(#<RSpec::ExampleGroups::Bar::Validators::WithBar>)> Bar.pluck(:foo)
=> [nil, "1664846482", "1664846482"]
[27] pry(#<RSpec::ExampleGroups::Bar::Validators::WithBar>)> Foo.pluck(:foo)
=> [nil, "QEVuQwFAEADedT4f//tkS+FfCFLwIeJbFHdo0Op7Bj/qGeqevSI8JA==", "QEVuQwFAEADUPnH12HAWk1Ic0ahIgN9BJAq5D8Vel5ZdPx9zQaP3yA=="]
```

Or do I something wrong?

**Comment by ahugofonseca** [comment]
I also had the same problem.

To maintain data integrity, I added a unique index to the database for the attribute I needed.

```
add_index :table, :foo, unique: true
```

Expecting a solution! :pray:

**Comment by larskuhnt** [comment]
I guess you need to set `random_iv` to `false` otherwise the encrypted value will always differ. This is also relevant if you want to query for `foo` with something like `Bar.where(foo: 'xyz')`, it will not work with a random initialisation vector.

```ruby
attribute :foo, :encrypted, random_id: false
```
