### ISSUE TITLE
Delete or update CHANGELOG.md

### ISSUE THREAD

**Issue by cyclotron3k** [rocketjob/symmetric-encryption#144]
`CHANGELOG.md` hasn't been updated for a while. Makes me a little nervous when new versions are published, but the changelog has no reference to the new version. In the past this has indicated a compromised gem. Makes me doubly nervous when the gem is security related.

I'd suggest either deleting `CHANGELOG.md` or updating it.

If you'd like to update it, but don't have the time I can probably submit a PR.

As usual, thanks for all your hard work.

**Comment by jaredbeck** [comment]
Was the changelog moved somewhere, or just deleted? I'm trying to determine if there were breaking changes between 4.3 and 4.4. Where would I find those documented, please, if any?

If you choose to reinstate a changelog, I can recommend the format and tips in https://keepachangelog.com/en/1.0.0/. I use it for my projects.

**Comment by reidmorrison** [comment]
If there are any breaking changes between versions they will be mentioned in the readme.md file, along with instructions on how to upgrade.

**Comment by jaredbeck** [comment]
Thanks for the reply, Reid. I will try to remember to look in the readme in the future. `CHANGELOG.md` is a very strong convention in the ruby community, though. It's where everyone is going to look first. But, it's your project :) Thanks for sharing your work, and best wishes for the new year.
