### ISSUE TITLE
Heroku support for non-rails apps

### ISSUE THREAD

**Issue by tombh** [rocketjob/symmetric-encryption#56]
I'm using this gem in a Grape app on a Heroku-like PaaS (therefore, no permanent file storage). So I couldn't use the Rails generator as described in the documentation. Instead, I had to do this:

``` ruby
require 'symmetric-encryption'
spec = Gem::Specification.find_by_name('symmetric-encryption')
gem_root = spec.gem_dir
template_path = File.join gem_root, '/lib/rails/generators/symmetric_encryption/heroku_config/templates/symmetric-encryption.yml'
template = ERB.new File.new(template_path).read, nil, '-'
puts template.result
```

Perhaps this could be made into a non-rails rake task?

**Comment by reidmorrison** [comment]
I agree, I need to create a symmetric-encryption bin file to generate this file, as well as to support file encryption / decryption without resorting to rake files or rails generators.

**Comment by reidmorrison** [comment]
Not forgetting this enhancement request, v4 has a new CLI that should finally make this a reality. An alpha of v4 should be available in the next week or two to try out.

**Comment by reidmorrison** [comment]
v4 is now at beta3 and includes this feature.
