### ISSUE TITLE
Virus test file causes header_present? method to fail

### ISSUE THREAD

**Issue by joshminnie** [rocketjob/symmetric-encryption#57]
We recently added virus scanning to our file transfer process, which we already used SymmetricEncryption to encrypt (uploade) and decrypt (download) the files. However when we use a sample virus file the `SymmetricEncryption::Reader.header_present?` call raises an `OpenSSL::Cipher::CipherError: wrong final block length` error.

The sample file is simply a text file with the body of

**eicar_test_file.txt**
```
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
```

**Comment by reidmorrison** [comment]
Sorry, I missed the github email notification for this issue somehow.

Trying to reproduce the issue via the console:

~~~ruby
SymmetricEncryption::VERSION
# "3.8.3"

SymmetricEncryption::Writer.open('eicar_test_file.txt.enc') {|f| f.write File.read("eicar_test_file.txt")}
# 69

SymmetricEncryption::Reader.open('eicar_test_file.txt.enc') {|f| f.read }
# "X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*\n"
~~~

Or, hopefully you have been able to resolve or workaround this issue?

**Comment by reidmorrison** [comment]
Configure your anti-virus software to not check `.enc` files since they are encrypted.
