### ISSUE TITLE
How to encrypt entire files at rest?

### ISSUE THREAD

**Issue by ChristofferJoergensen** [rocketjob/symmetric-encryption#58]
Greetings. I am using this gem to encrypt db fields. I can read from the readme:

> Encrypt entire files at rest

However, I don't think the documentation specifies how to do that. Specifically, I am using carrierwave to store uploaded images. However, I would like to encrypt them as .enc files before. Is that possible?

**Comment by reidmorrison** [comment]
The file API is currently only covered in the reference guide:
http://www.rubydoc.info/gems/symmetric-encryption/SymmetricEncryption/Writer

http://www.rubydoc.info/gems/symmetric-encryption/SymmetricEncryption/Reader

**Comment by reidmorrison** [comment]
Let me know if the above links were not sufficient. Ideally file encryption should be properly documented in the guides.
