### ISSUE TITLE
new_keys generator raises undefined method 'encrypt_key'

### ISSUE THREAD

**Issue by eliotsykes** [rocketjob/symmetric-encryption#59]
Running this rails generator in symmetric-encryption 3.8.3:

```sh
bin/rails generate symmetric_encryption:new_keys production
```

Produced the following error:
```
Generated new Symmetric Key for encryption
vendor/bundle/gems/symmetric-encryption-3.8.3/lib/symmetric_encryption/cipher.rb:74:in
`generate_random_keys': 
  undefined method `encrypt_key' for SymmetricEncryption::Cipher:Class (NoMethodError)

  from vendor/bundle/gems/symmetric-encryption-3.8.3/lib/symmetric_encryption/symmetric_encryption.rb:275:in `generate_symmetric_key_files'
  from vendor/bundle/gems/symmetric-encryption-3.8.3/lib/rails/generators/symmetric_encryption/new_keys/new_keys_generator.rb:9:in `create_config_file'
```

Managed to replicate the issue from the rails console with:

```rb
SymmetricEncryption::Cipher.generate_random_keys(encrypted_key: '')
```

It appears the `Cipher#encrypt_key` instance method is expected to be a class method.

**Comment by reidmorrison** [comment]
Thank you for reporting this issue. The fix is now available in master, will have a new gem out soon with this fix.

**Comment by ashkan18** [comment]
Have you had a chance to push the latest gem version? Seeing this issue in `3.8.3`, thanks 😃

**Comment by reidmorrison** [comment]
@ashkan18 Thank you for the reminder. I have published the long overdue gem update. v3.9.0

**Comment by ashkan18** [comment]
awesome! thanks @reidmorrison
