### ISSUE TITLE
HIPAA Compliance

### ISSUE THREAD

**Issue by magicmarkker** [rocketjob/symmetric-encryption#61]
HIPAA is spelled HIPPA everywhere in the documentation when the correct way is HIPAA :)

**Comment by reidmorrison** [comment]
Good catch, want to submit a pull request?

**Comment by magicmarkker** [comment]
Hah, nevermind its only on the [http://rocketjob.github.io/symmetric-encryption/](http://rocketjob.github.io/symmetric-encryption/) pages, which the repo doesn't have in the source so I can't pull request for those. I'll close this issue :)

**Comment by reidmorrison** [comment]
The documentation is in this repo on the branch gh-pages. Not a problem I will push the updated abbreviation.
