### ISSUE TITLE
Not work with ruby 2.4

### ISSUE THREAD

**Issue by taka0125** [rocketjob/symmetric-encryption#70]
[This Sample](http://rocketjob.github.io/symmetric-encryption/standalone.html) not work with ruby 2.4.

```
vendor/bundle/ruby/2.4.0/gems/symmetric-encryption-3.8.3/lib/symmetric_encryption/cipher.rb:468:in `key=': key must be 16 bytes (ArgumentError)
```

Code is here.

https://github.com/taka0125/symmetric-encryption-ruby2.4

**Comment by reidmorrison** [comment]
With Ruby 2.4 it now verifies the length of the key to ensure it matches the cipher. 

Please change:
~~~ruby
SymmetricEncryption.cipher = SymmetricEncryption::Cipher.new(
  cipher_name: 'aes-128-cbc',
  key:         '1234567890ABCDEF1234567890ABCDEF',
  iv:          '1234567890ABCDEF',
  encoding:    :base64strict
)
~~~

Truncating the key to:
~~~ruby
SymmetricEncryption.cipher = SymmetricEncryption::Cipher.new(
  cipher_name: 'aes-128-cbc',
  key:         '1234567890ABCDEF',
  iv:          '1234567890ABCDEF',
  encoding:    :base64strict
)
~~~

Prior to Ruby 2.4 it just truncated the key when it was too long. 

The documentation examples use a key that is too long and will be fixed to use the correct length, per the example above.
