### ISSUE TITLE
Better standalone support

### ISSUE THREAD

**Issue by amedeiros** [rocketjob/symmetric-encryption#75]
I know using Symmetric Encryption with rails is pretty straight forward. However, trying to use it outside of rails can be cumbersome especially for generating configurations etc. How do you feel about a symmetric-encryption executable to be packaged with the gem to aid in generating outside of a rails application?

**Comment by reidmorrison** [comment]
Absolutely love the idea. :tada:
Would be awesome if the bin file could also replace the existing rake tasks.

**Comment by amedeiros** [comment]
If I get a chance this week I can take a crack at it. I did something similar for my Groovy library. https://github.com/amedeiros/symmetric-encryption/blob/master/README.md#command-line-runner-usage .

**Comment by amedeiros** [comment]
This is what I got going so far.

```
symmetric-encryption <options>
    -e, --encrypt                    Encrypt a plain text value. Requires --env and --file.
    -d, --decrypt VALUE              Decrypt a encrypted value. Requires --env and --file.
    -r, --random                     Generate a random password.
    -k, --keys                       Generate encryption keys Requires --env and --file.
    -c, --config                     Generate a configuration file. Requires --path and --name
    -p, --path KEY_PATH              Key path for configuration generator.
    -n, --name NAME                  Name for configuration generator
    -v, --env ENVIRONMENT            Which environment are we using.
    -f, --file FILE_PATH             File path of your configuration file.
```

```
± |master S:1 U:3 ?:2 ✗| → symmetric-encryption --encrypt --env development --file ~/Documents/ruby_projects/symmetric-encryption-1/examples/symmetric-encryption.yml
Enter the value to encrypt:
*********
Re-enter the value to encrypt:
*********

Encrypted: ClfV19NzS/hjZeAMGHOTOA==

± |master S:1 U:3 ?:2 ✗| → symmetric-encryption --decrypt ClfV19NzS/hjZeAMGHOTOA== --env development --file ~/Documents/ruby_projects/symmetric-encryption-1/examples/symmetric-encryption.yml
Decrypted: PlainText

± |master S:1 U:3 ?:2 ✗| → symmetric-encryption -r --env development --file ~/Documents/ruby_projects/symmetric-encryption-1/examples/symmetric-encryption.yml

Generated Password: 9vL5RCntPkoDoQ9zshmV+w
Encrypted: YMBUjk74WoIsjixxYviHc+hme1XlXyMx8CU+rrDMlaA=

± |master S:1 U:3 ?:2 ✗| → symmetric-encryption -k --env development --file ~/Documents/ruby_projects/symmetric-encryption-1/examples/symmetric-encryption.yml

Please add the key: F/MVgcK62zaX2erG9LLKJA== to your config file
Please add the iv: 4aWpVlv9eLuKMWBML3Td2w== to your config file

± |master S:1 U:3 ?:2 ✗| → symmetric-encryption -c --path /etc/rails --name test_app
New configuration at: /Users/amedeiros/Documents/ruby_projects/symmetric-encryption-1/config/symmetric-encryption.yml
```

**Comment by reidmorrison** [comment]
Very nice, looking forward to giving it a try. 👍

**Comment by reidmorrison** [comment]
Thank you @amedeiros for the PR.

When do you want a gem release?

Now that I think about it we can add docs for it under `/docs/rake_tasks.md`. Then we can rename that page and its link. To see the docs as they are changed:
* cd docs
* bundle
* `jekyll serve`

I wonder how difficult it would be to add heroku support: https://github.com/rocketjob/symmetric-encryption/issues/56

**Comment by amedeiros** [comment]
As far as a new gem release I'm in no rush. I wanted the standalone support for a open source project I'm working on https://github.com/amedeiros/micro-rb. My CLI for the project generator has an option to include symmetric-encryption but I wanted to also generate the symmetric encryption config file. Figured it would be better to just contribute that in the form of a bin file.

**Comment by reidmorrison** [comment]
v4 of Symmetric Encryption is now at beta3 and includes an all new CLI that addresses the above issues.
