### ISSUE TITLE
Setting attribute to empty string changes it to null

### ISSUE THREAD

**Issue by airblade** [rocketjob/symmetric-encryption#77]
I have a Rails 5 app with a model which has an encrypted attribute.

```ruby
class User < ApplicationRecord
  attr_encrypted :foo, random_iv: true
end
```

When I set `foo` to an empty string and save, the system tries to update `foo` in the database with a `nil` value.  I would expect it to send an empty string to the database, not `nil`.

```ruby
>> u = User.last
>> u.foo = 'bar'    # this works as expected
>> u.save
=> UPDATE "users" SET "encrypted_foo" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["encrypted_foo", "QEVuQwBAEAC8lTgA/00QFleREee9wARnATR8ZA78uN/MxVogSDjftA=="], ["updated_at", 2017-05-16 15:32:45 UTC], ["id", 1]]

>> u.foo = ''    # this does not work as expected
>> u.save
=> UPDATE "users" SET "encrypted_foo" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["encrypted_foo", nil], ["updated_at", 2017-05-16 15:32:45 UTC], ["id", 1]]
```

I'm using symmetric-encryption 3.9.0, rails 5.0.1.

**Comment by airblade** [comment]
The [generator coerces](https://github.com/rocketjob/symmetric-encryption/blob/v3.9.0/lib/symmetric_encryption/generator.rb#L27) the empty string:

```ruby
v = SymmetricEncryption::Coerce.coerce(value, :#{type})
```

– and the coercion turns the [empty string into nil](https://github.com/rocketjob/symmetric-encryption/blob/v3.9.0/lib/symmetric_encryption/coerce.rb#L17):

```ruby
return if blank?(value)
```

Shouldn't "coercing" a plain text attribute (as opposed to JSON or YAML) to a string leave it untouched?  And, in this case, leave an empty string as an empty string?

**Comment by dpneumo** [comment]
Have noticed the same behavior and agree the appropriate behavior is to leave an empty string as an empty string after coercion.

**Comment by reidmorrison** [comment]
Agreed, looked at briefly but looks like it is deep in the Coerce code somewhere.

Definitely want this to be fixed though as converting nil to '' is not expected behavior.

**Comment by airblade** [comment]
Thanks!

**Comment by dpneumo** [comment]
Thanks.
