### ISSUE TITLE
CLI not respecting --envs (or --environments option)

### ISSUE THREAD

**Issue by lostmahbles** [rocketjob/symmetric-encryption#81]
On latest master (4.0.0.beta2) when running the CLI using
```
symmetric-encryption --generate --environments "development,test,preprod,acceptance,production"
```
The config file still only has development, test, release and production entries. It doesn't seem to respect the `--environments` option at all. (Using --env as is in the docs results in an option not supported error).

**Comment by lostmahbles** [comment]
It looks like, for some reason the line
```
environments ||= %i(development test release production)
```
in cli.rb overwrites `environments` even though `environments` contains the CLI options. Adding the line
```
environments ||= @environments
```
just above it makes it work as intended, but for the life of me I have no idea why.

**Comment by reidmorrison** [comment]
Thank you for the feedback, good to see people are trying out the beta release.

Be sure to re-generate the config file when v4 is finally released. We are busy with some under the covers changes to the way key encrypting keys are handled based on feedback from a new PCI DSS auditing firm.
