### ISSUE TITLE
Padding Check Failed

### ISSUE THREAD

**Issue by mmaruri** [rocketjob/symmetric-encryption#82]
I get this error when trying to deploy to heroku.  I get it when running `RAILS_ENV=production bundle exec rake -P --trace` as well but I'm not sure what exactly is causing it.  Any help would be appreciated

`D, [2017-09-18T13:38:46.166872 #37661] DEBUG -- : ** [Raven] Event not sent due to excluded environment: production
rake aborted!
OpenSSL::PKey::RSAError: padding check failed
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/key_encryption_key.rb:25:in `private_decrypt'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/key_encryption_key.rb:25:in `decrypt'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/cipher.rb:239:in `initialize'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/config.rb:65:in `new'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/config.rb:65:in `block in extract_ciphers'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/config.rb:64:in `collect'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/config.rb:64:in `extract_ciphers'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/config.rb:13:in `load!'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/symmetric-encryption-3.9.1/lib/symmetric_encryption/railtie.rb:41:in `block in <class:Railtie>'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:147:in `run_load_hooks!'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:95:in `instance'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:123:in `config'
/Users/mmaruri/code/flexible-learning-lti/config/application.rb:19:in `<class:Application>'
/Users/mmaruri/code/flexible-learning-lti/config/application.rb:10:in `<module:FlexibleLearning>'
/Users/mmaruri/code/flexible-learning-lti/config/application.rb:9:in `<top (required)>'
/Users/mmaruri/code/flexible-learning-lti/Rakefile:4:in `require'
/Users/mmaruri/code/flexible-learning-lti/Rakefile:4:in `<top (required)>'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/mmaruri/.rbenv/versions/2.2.7/bin/rake:23:in `load'
/Users/mmaruri/.rbenv/versions/2.2.7/bin/rake:23:in `<top (required)>'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/mmaruri/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/Users/mmaruri/.rbenv/versions/2.2.7/bin/bundle:23:in `load'
/Users/mmaruri/.rbenv/versions/2.2.7/bin/bundle:23:in `<main>'
`

**Comment by codesoda** [comment]
@mmaruri do you remember what your solution was?

**Comment by mmaruri** [comment]
@codesoda sorry for the late reply.  It was due to the encrypted_key not being set in the symmetric-encryption.yml.
