### ISSUE TITLE
Multi-environment usage

### ISSUE THREAD

**Issue by ThisIsMissEm** [rocketjob/symmetric-encryption#87]
Currently we configuring symmetric-encryption, you can specify each of the environments that you have (e.g., say if you have a demo or staging environment). This works well, but there's an issue: The default way to determine which "environment" symmetric-encryption should use is to look at `Rails.env`

However, Heroku recommends against multiple "environments" ([details](https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment)), so in order to work nicely with heroku `Rails.env` has to be just "production"

It seems that it'd be possible to read from something else, given the contents of [railties](https://github.com/rocketjob/symmetric-encryption/blob/master/lib/symmetric_encryption/railtie.rb#L31-L50)

I'd like to field interest in setting up an `ENCRYPTION_ENV` variable as an alternative to use `Rails.env` (i.e., env = ENV['ENCRYPTION_ENV'] || Rails.env).

This way I could still have multiple encryption environments and still play nicely with heroku.

**Comment by reidmorrison** [comment]
Symmetric Encryption supports both environment variables and Heroku directly. Look for the Heroku option when generating the configuration file:
https://rocketjob.github.io/symmetric-encryption/configuration.html

**Comment by ThisIsMissEm** [comment]
The problem is with `--envs ENVIRONMENTS`, say I have a heroku pipeline setup with production and release apps, in order to instruct symmetric-encryption which keys to use for which app, I need to pass `RAILS_ENV=production` or `RAILS_ENV=release`, this is problematic because heroku thinks that `release` isn't a production-like environment. Additionally anything that does optimisations for `Rails.env.production?` will consequently not be optimised in `release` but will be optimised in `production`

Hence wanting a way to have `RAILS_ENV=production` in both apps, but use different symmetric-encryption keys. As proposed, having a environment variable specifically for symmetric-encryption to use to understand it's environment.

**Comment by ThisIsMissEm** [comment]
It's where the `env` at the end of this line comes from which is the problem: https://github.com/rocketjob/symmetric-encryption/blob/6668880e659672a5c724fd2db63c01cfb05590b7/lib/symmetric_encryption/config.rb#L76

**Comment by reidmorrison** [comment]
@ThisIsMissEm The above PR has been merged, does it sufficiently address the requirements above?
