### ISSUE TITLE
Can't get array column to encrypt

### ISSUE THREAD

**Issue by airblade** [rocketjob/symmetric-encryption#91]
Hello!

I am trying to encrypt an ActiveRecord array column (for use with Postgresql).  Without encryption it looks like:

```ruby
# migration
add_column :foos, :bars, :text, array: true
```

I thought the encrypted version would look like this, but it doesn't work:

```ruby
# migration
add_column :foos, :encrypted_bars, :text, array: true

# model
class Foo < ApplicationRecord
  attr_encrypted :bars, type: :json, random_iv: true
end
```

I also tried (a) without the `type: :json`, and (b) with a column type of `:string`, but those didn't work either.  When I try to save the array, it gets turned into an empty string.

Am I going about this the wrong way, or is it not supported?

I'm using symmetric-encryption 3.9.1, rails 5.1.4.

Thanks!

**Comment by reidmorrison** [comment]
We don't use Postgresql. The array type works fine with MySQL and :text column types.

**Comment by airblade** [comment]
OK, thanks for clarifying.
